fix: missing dep. @codemirror/autocomplete
To avoid error on `yarn run build`:

```
src/extensions.ts:8:85: error: Could not resolve "@codemirror/autocomplete" (mark it as external to exclude it from the bundle)
    8 │ import { autocompletion, closeBrackets, closeBracketsKeymap, completionKeymap } from "@codemirror/autocomplete";

    Error: Build failed with 1 error:
    src/extensions.ts:8:85: error: Could not resolve "@codemirror/autocomplete" (mark it as external to exclude it from the bundle)
```